# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pet_chat_pb2 as pet__chat__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pet_chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PetChatServiceStub(object):
    """==========================================
    核心服务定义 (Service)
    这就是腾讯 JD 里要求的“高并发 RPC 服务的设计”
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/pet.PetChatService/GetStatus',
                request_serializer=pet__chat__pb2.StatusRequest.SerializeToString,
                response_deserializer=pet__chat__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AskPetStream = channel.unary_stream(
                '/pet.PetChatService/AskPetStream',
                request_serializer=pet__chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=pet__chat__pb2.ChatResponse.FromString,
                _registered_method=True)


class PetChatServiceServicer(object):
    """==========================================
    核心服务定义 (Service)
    这就是腾讯 JD 里要求的“高并发 RPC 服务的设计”
    ==========================================
    """

    def GetStatus(self, request, context):
        """1. 基础调用 (Unary RPC)：一问一答，适合极速拉取数据
        场景：前端每隔 10 秒偷偷问一下后端“桌宠现在饿不饿？”
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskPetStream(self, request, context):
        """2. 流式调用 (Server Streaming RPC)：大模型场景的灵魂！
        场景：用户输入复杂问题，AI Agent 思考并逐字返回结果，注意这里的 stream 关键字
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=pet__chat__pb2.StatusRequest.FromString,
                    response_serializer=pet__chat__pb2.StatusResponse.SerializeToString,
            ),
            'AskPetStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskPetStream,
                    request_deserializer=pet__chat__pb2.ChatRequest.FromString,
                    response_serializer=pet__chat__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pet.PetChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pet.PetChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PetChatService(object):
    """==========================================
    核心服务定义 (Service)
    这就是腾讯 JD 里要求的“高并发 RPC 服务的设计”
    ==========================================
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pet.PetChatService/GetStatus',
            pet__chat__pb2.StatusRequest.SerializeToString,
            pet__chat__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskPetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pet.PetChatService/AskPetStream',
            pet__chat__pb2.ChatRequest.SerializeToString,
            pet__chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
