# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet_chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pet_chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epet_chat.proto\x12\x03pet\"\x1f\n\rStatusRequest\x12\x0e\n\x06pet_id\x18\x01 \x01(\t\"4\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmood_score\x18\x02 \x01(\x05\"/\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"J\n\x0c\x43hatResponse\x12\x12\n\ntext_chunk\x18\x01 \x01(\t\x12\x13\n\x0b\x61gent_state\x18\x02 \x01(\t\x12\x11\n\tis_finish\x18\x03 \x01(\x08\x32}\n\x0ePetChatService\x12\x34\n\tGetStatus\x12\x12.pet.StatusRequest\x1a\x13.pet.StatusResponse\x12\x35\n\x0c\x41skPetStream\x12\x10.pet.ChatRequest\x1a\x11.pet.ChatResponse0\x01\x42\x12Z\x10../go-gateway/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020../go-gateway/pb'
  _globals['_STATUSREQUEST']._serialized_start=23
  _globals['_STATUSREQUEST']._serialized_end=54
  _globals['_STATUSRESPONSE']._serialized_start=56
  _globals['_STATUSRESPONSE']._serialized_end=108
  _globals['_CHATREQUEST']._serialized_start=110
  _globals['_CHATREQUEST']._serialized_end=157
  _globals['_CHATRESPONSE']._serialized_start=159
  _globals['_CHATRESPONSE']._serialized_end=233
  _globals['_PETCHATSERVICE']._serialized_start=235
  _globals['_PETCHATSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
