# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpet.proto\x12\x03pet\"2\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\tChatReply\x12\r\n\x05reply\x18\x01 \x01(\t\"[\n\x0f\x41uthRegisterReq\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08pet_name\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\"5\n\x11\x41uthRegisterReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"6\n\x0c\x41uthLoginReq\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"T\n\x0e\x41uthLoginReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08pet_name\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t2\xb5\x01\n\nPetService\x12*\n\x04\x43hat\x12\x10.pet.ChatRequest\x1a\x0e.pet.ChatReply\"\x00\x12\x41\n\x0fRegisterAccount\x12\x14.pet.AuthRegisterReq\x1a\x16.pet.AuthRegisterReply\"\x00\x12\x38\n\x0cLoginAccount\x12\x11.pet.AuthLoginReq\x1a\x13.pet.AuthLoginReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=18
  _globals['_CHATREQUEST']._serialized_end=68
  _globals['_CHATREPLY']._serialized_start=70
  _globals['_CHATREPLY']._serialized_end=96
  _globals['_AUTHREGISTERREQ']._serialized_start=98
  _globals['_AUTHREGISTERREQ']._serialized_end=189
  _globals['_AUTHREGISTERREPLY']._serialized_start=191
  _globals['_AUTHREGISTERREPLY']._serialized_end=244
  _globals['_AUTHLOGINREQ']._serialized_start=246
  _globals['_AUTHLOGINREQ']._serialized_end=300
  _globals['_AUTHLOGINREPLY']._serialized_start=302
  _globals['_AUTHLOGINREPLY']._serialized_end=386
  _globals['_PETSERVICE']._serialized_start=389
  _globals['_PETSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
